# Generated by Django 5.1.3 on 2024-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
