# Generated by Django 5.1.3 on 2024-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_delete_customer_servicerequest_attached_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Repair', 'Repair'), ('Billing', 'Billing')], default='Installation', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
